### ISSUE TITLE
Subcomponent fetchdata

### ISSUE THREAD

**Issue by lineldcosta** [dylants/universal#1]
I loved the way u have showed the SSR, Is there any solution with react-router 4 to fetch the data from subcomponents. I mean components which are imported in the container?

**Comment by dylants** [comment]
Sorry for the delay in responding, I didn't see this issue until now. I typically don't fetch data in components, but instead in the containers and pass that data into the components. This tends to keep the components pure and "dumb" so that they can be reused outside of the application, and also tested without needing to wire up the APIs.

But really the only difference between the container and the component is the naming. It's just a pattern I apply to try and logically separate the code.

Hope that helps!
